### ISSUE TITLE
TypeError, helpme

### ISSUE THREAD

**Issue by GabrielMendesdc** [cleitonleonel/xml2pdf#1]
Traceback (most recent call last):
  File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 280, in <module>
    initialize(file_path)
  File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 236, in initialize
    "payments": get_payments(payments),
  File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 180, in get_payments
    html_str = f'{get_payment_type(payment["tPag"])}<span class="td-text-right">{payment["vPag"]}</span>'
TypeError: string indices must be integers

**Comment by cleitonleonel** [comment]
> Traceback (most recent call last): File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 280, in initialize(file_path) File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 236, in initialize "payments": get_payments(payments), File "C:\Users\pdv\Documents\GitHub\xml2pdf\conversor.py", line 180, in get_payments html_str = f'{get_payment_type(payment["tPag"])}{payment["vPag"]}' TypeError: string indices must be integers

Ok, pode me enviar o modelo de xml utilizado nessa tentativa, o que resultou nesse erro??? Essa funcionalidade de incluir os tipos de pagamentos detalhados e auto descritivos foi adicionada recentemente e nem tive o prazer de testar todas as possibilidades.
Fico grato se puder fornecer esse xml para que eu possa corrigir esse bug.

**Comment by GabrielMendesdc** [comment]
<?xml version="1.0" encoding="utf-8"?><nfeProc versao="4.00" xmlns="http://www.portalfiscal.inf.br/nfe"><NFe xmlns="http://www.portalfiscal.inf.br/nfe"><infNFe versao="4.00" Id="NFe35210803259185000141550010008411981008412000"><ide><cUF>35</cUF><cNF>00841200</cNF><natOp>VENDA A PRAZO</natOp><mod>55</mod><serie>1</serie><nNF>841198</nNF><dhEmi>2021-08-18T00:00:00-03:00</dhEmi><dhSaiEnt>2021-08-19T00:00:00-03:00</dhSaiEnt><tpNF>1</tpNF><idDest>1</idDest><cMunFG>3509502</cMunFG><tpImp>0</tpImp><tpEmis>1</tpEmis><cDV>0</cDV><tpAmb>1</tpAmb><finNFe>1</finNFe><indFinal>0</indFinal><indPres>0</indPres><procEmi>0</procEmi><verProc>Pontual - 7.2.32</verProc></ide><emit><CNPJ>03259185000141</CNPJ><xNome>AVEC CAMPINAS DISTRIBUIDORA LTDA</xNome><xFant>AVEC CAMPINAS DISTRIBUIDORA LTDA</xFant><enderEmit><xLgr>AV. RICARDO BASSOLI CEZARE</xLgr><nro>281</nro><xBairro>JD SAO JOSE</xBairro><cMun>3509502</cMun><xMun>CAMPINAS</xMun><UF>SP</UF><CEP>13050080</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1932680251</fone></enderEmit><IE>244647118116</IE><CRT>3</CRT></emit><dest><CNPJ>07246178000166</CNPJ><xNome>SHOPPING FARTURA COMERCIO DE HORTIFRUTIGRANJEIROS LTDA</xNome><enderDest><xLgr>RUA JORGE DE FIGUEIREDO CORREA</xLgr><nro>1727</nro><xBairro>CHAC PRIMAVERA</xBairro><cMun>3509502</cMun><xMun>CAMPINAS</xMun><UF>SP</UF><CEP>13087490</CEP><cPais>1058</cPais><xPais>BRASIL</xPais><fone>1932569489</fone></enderDest><indIEDest>1</indIEDest><IE>244985022114</IE></dest><det nItem="1"><prod><cProd>6021</cProd><cEAN>17891079000202</cEAN><xProd>LACN - LAMEN CARNE 50X85GR 50X85GRS</xProd><NCM>19023000</NCM><CEST>1704701</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>77.0000000000</vUnCom><vProd>77.00</vProd><cEANTrib>7891079000205</cEANTrib><uTrib>UNI</uTrib><qTrib>50.0000</qTrib><vUnTrib>1.5400000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>5</orig><CST>60</CST><vBCSTRet>82.32</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>5.99</vICMSSubstituto><vICMSSTRet>8.77</vICMSSTRet></ICMS60></ICMS><PIS><PISNT><CST>06</CST></PISNT></PIS><COFINS><COFINSNT><CST>06</CST></COFINSNT></COFINS></imposto></det><det nItem="2"><prod><cProd>6031</cProd><cEAN>17891079000226</cEAN><xProd>LAGO - LAMEN GALINHA CAIPIRA 50X85GR 50X85GRS</xProd><NCM>19023000</NCM><CEST>1704701</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>77.0000000000</vUnCom><vProd>77.00</vProd><cEANTrib>7891079000229</cEANTrib><uTrib>UNI</uTrib><qTrib>50.0000</qTrib><vUnTrib>1.5400000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>5</orig><CST>60</CST><vBCSTRet>82.32</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>5.99</vICMSSubstituto><vICMSSTRet>8.77</vICMSSTRet></ICMS60></ICMS><PIS><PISNT><CST>06</CST></PISNT></PIS><COFINS><COFINSNT><CST>06</CST></COFINSNT></COFINS></imposto></det><det nItem="3"><prod><cProd>6051</cProd><cEAN>17891079000240</cEAN><xProd>LALL - LAMEN LEGUMES 50X85GR 50X85GRS</xProd><NCM>19023000</NCM><CEST>1704701</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>77.0000000000</vUnCom><vProd>77.00</vProd><cEANTrib>7891079000243</cEANTrib><uTrib>UNI</uTrib><qTrib>50.0000</qTrib><vUnTrib>1.5400000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>5</orig><CST>60</CST><vBCSTRet>82.32</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>5.99</vICMSSubstituto><vICMSSTRet>8.77</vICMSSTRet></ICMS60></ICMS><PIS><PISNT><CST>06</CST></PISNT></PIS><COFINS><COFINSNT><CST>06</CST></COFINSNT></COFINS></imposto></det><det nItem="4"><prod><cProd>1023</cProd><cEAN>7891132012015</cEAN><xProd>AJINOMOTO C/36 REFIL X100GRS UNIDADE</xProd><NCM>29224220</NCM><CFOP>5102</CFOP><uCom>UND</uCom><qCom>18.0000</qCom><vUnCom>4.1400000000</vUnCom><vProd>74.52</vProd><cEANTrib>7891132012015</cEANTrib><uTrib>UNI</uTrib><qTrib>18.0000</qTrib><vUnTrib>4.1400000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS00><orig>5</orig><CST>00</CST><modBC>3</modBC><vBC>74.52</vBC><pICMS>18.0000</pICMS><vICMS>13.41</vICMS></ICMS00></ICMS><PIS><PISAliq><CST>01</CST><vBC>61.11</vBC><pPIS>1.6500</pPIS><vPIS>1.01</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>61.11</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>4.64</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="5"><prod><cProd>1391</cProd><cEAN>17891132080035</cEAN><xProd>AJI-SAL CHURRASCO 500GRX24UN 24X500GRS</xProd><NCM>21039021</NCM><CEST>1703500</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>132.4800000000</vUnCom><vProd>132.48</vProd><cEANTrib>7891132080038</cEANTrib><uTrib>UNI</uTrib><qTrib>24.0000</qTrib><vUnTrib>5.5200000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>5</orig><CST>60</CST><vBCSTRet>138.23</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>9.83</vICMSSubstituto><vICMSSTRet>14.66</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>132.48</vBC><pPIS>1.6500</pPIS><vPIS>2.19</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>132.48</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>10.07</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="6"><prod><cProd>13913</cProd><cEAN>7891132006380</cEAN><xProd>SAZON - CALDO LEGUMES C/48 X37,5GRS UNIDADE</xProd><NCM>21041011</NCM><CFOP>5102</CFOP><uCom>UND</uCom><qCom>24.0000</qCom><vUnCom>1.3300000000</vUnCom><vProd>31.92</vProd><cEANTrib>7891132006380</cEANTrib><uTrib>UNI</uTrib><qTrib>24.0000</qTrib><vUnTrib>1.3300000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS20><orig>5</orig><CST>20</CST><modBC>3</modBC><pRedBC>33.3300</pRedBC><vBC>21.28</vBC><pICMS>18.0000</pICMS><vICMS>3.83</vICMS></ICMS20></ICMS><PIS><PISAliq><CST>01</CST><vBC>28.09</vBC><pPIS>1.6500</pPIS><vPIS>0.46</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>28.09</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>2.13</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="7"><prod><cProd>96391</cProd><cEAN>17898024396991</cEAN><xProd>ROCHER T12X9 9X12UN</xProd><NCM>18069000</NCM><CEST>1700700</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>193.3200000000</vUnCom><vProd>193.32</vProd><cEANTrib>7898024396994</cEANTrib><uTrib>UNI</uTrib><qTrib>9.0000</qTrib><vUnTrib>21.4800000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>169.07</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>15.12</vICMSSubstituto><vICMSSTRet>15.31</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>193.32</vBC><pPIS>1.6500</pPIS><vPIS>3.19</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>193.32</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>14.69</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="8"><prod><cProd>13762</cProd><cEAN>7898024393191</cEAN><xProd>TIC TAC LARANJA T14X24 14 UNIDADE</xProd><NCM>17049020</NCM><CFOP>5102</CFOP><uCom>DP</uCom><qCom>1.0000</qCom><vUnCom>21.2600000000</vUnCom><vProd>21.26</vProd><cEANTrib>78600027</cEANTrib><uTrib>UNI</uTrib><qTrib>14.0000</qTrib><vUnTrib>1.5185714286</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS20><orig>5</orig><CST>20</CST><modBC>3</modBC><pRedBC>33.3300</pRedBC><vBC>14.17</vBC><pICMS>18.0000</pICMS><vICMS>2.55</vICMS></ICMS20></ICMS><PIS><PISAliq><CST>01</CST><vBC>18.71</vBC><pPIS>1.6500</pPIS><vPIS>0.31</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>18.71</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>1.42</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="9"><prod><cProd>10251</cProd><cEAN>27896007811001</cEAN><xProd>SAKURA TRADICIONAL 24X150ML 24X150ML</xProd><NCM>21031010</NCM><CEST>1703600</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>59.0300000000</vUnCom><vProd>59.03</vProd><cEANTrib>7896007811007</cEANTrib><uTrib>UNI</uTrib><qTrib>24.0000</qTrib><vUnTrib>2.4595833333</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>65.85</vBCSTRet><pST>12.0000</pST><vICMSSubstituto>3.69</vICMSSubstituto><vICMSSTRet>5.03</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>59.03</vBC><pPIS>1.6500</pPIS><vPIS>0.97</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>59.03</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>4.49</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="10"><prod><cProd>7431</cProd><cEAN>27896007811407</cEAN><xProd>KENKO INGLES DKV 24X150ML 24X150ML</xProd><NCM>21039021</NCM><CEST>1703500</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>3.0000</qCom><vUnCom>53.6700000000</vUnCom><vProd>161.01</vProd><cEANTrib>7896007811403</cEANTrib><uTrib>UNI</uTrib><qTrib>72.0000</qTrib><vUnTrib>2.2362500000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>170.95</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>10.25</vICMSSubstituto><vICMSSTRet>11.81</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>161.01</vBC><pPIS>1.6500</pPIS><vPIS>2.66</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>161.01</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>12.24</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="11"><prod><cProd>90831</cProd><cEAN>27896007800050</cEAN><xProd>SAKURA LIGHT PET 24X150ML 24X150ML</xProd><NCM>21031010</NCM><CEST>1703600</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>66.5800000000</vUnCom><vProd>66.58</vProd><cEANTrib>7896007800056</cEANTrib><uTrib>UNI</uTrib><qTrib>24.0000</qTrib><vUnTrib>2.7741666667</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>74.28</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>7.11</vICMSSubstituto><vICMSSTRet>5.67</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>66.58</vBC><pPIS>1.6500</pPIS><vPIS>1.10</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>66.58</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>5.06</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="12"><prod><cProd>8461</cProd><cEAN>27896007800890</cEAN><xProd>MOLHO SAKURA YAKISSOBA 24X500ML 24X500ML</xProd><NCM>21031010</NCM><CEST>1703600</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>262.5800000000</vUnCom><vProd>262.58</vProd><cEANTrib>7896007800896</cEANTrib><uTrib>UNI</uTrib><qTrib>24.0000</qTrib><vUnTrib>10.9408333333</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>292.96</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>26.58</vICMSSubstituto><vICMSSTRet>22.38</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>262.58</vBC><pPIS>1.6500</pPIS><vPIS>4.33</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>262.58</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>19.96</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="13"><prod><cProd>23121</cProd><cEAN>17896007870551</cEAN><xProd>FARINHA PARA EMPANAR PANKO 12X200GRS 12X200GRS</xProd><NCM>19019090</NCM><CFOP>5102</CFOP><uCom>CX</uCom><qCom>1.0000</qCom><vUnCom>93.4500000000</vUnCom><vProd>93.45</vProd><cEANTrib>7896007870554</cEANTrib><uTrib>UNI</uTrib><qTrib>12.0000</qTrib><vUnTrib>7.7875000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS20><orig>2</orig><CST>20</CST><modBC>3</modBC><pRedBC>33.3300</pRedBC><vBC>62.30</vBC><pICMS>18.0000</pICMS><vICMS>11.21</vICMS></ICMS20></ICMS><PIS><PISAliq><CST>01</CST><vBC>82.24</vBC><pPIS>1.6500</pPIS><vPIS>1.36</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>82.24</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>6.25</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="14"><prod><cProd>3863</cProd><cEAN>7896007857210</cEAN><xProd>MISSO SHIRO POTE 24X500GRS UNIDADE</xProd><NCM>21039091</NCM><CEST>1703500</CEST><CFOP>5405</CFOP><uCom>UND</uCom><qCom>6.0000</qCom><vUnCom>12.1800000000</vUnCom><vProd>73.08</vProd><cEANTrib>7896007857210</cEANTrib><uTrib>UNI</uTrib><qTrib>6.0000</qTrib><vUnTrib>12.1800000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>77.58</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>7.53</vICMSSubstituto><vICMSSTRet>5.36</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>73.08</vBC><pPIS>1.6500</pPIS><vPIS>1.21</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>73.08</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>5.55</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="15"><prod><cProd>3893</cProd><cEAN>7896007857203</cEAN><xProd>MISSO AKA POTE 24X500GRS UNIDADE</xProd><NCM>21039091</NCM><CEST>1703500</CEST><CFOP>5405</CFOP><uCom>UND</uCom><qCom>6.0000</qCom><vUnCom>11.0500000000</vUnCom><vProd>66.30</vProd><cEANTrib>7896007857203</cEANTrib><uTrib>UNI</uTrib><qTrib>6.0000</qTrib><vUnTrib>11.0500000000</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>70.33</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>7.59</vICMSSubstituto><vICMSSTRet>4.86</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>66.30</vBC><pPIS>1.6500</pPIS><vPIS>1.09</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>66.30</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>5.04</vCOFINS></COFINSAliq></COFINS></imposto></det><det nItem="16"><prod><cProd>71</cProd><cEAN>17896007865977</cEAN><xProd>MOLHO TARE PET 12X180ML 12X180ML</xProd><NCM>21039021</NCM><CEST>1703500</CEST><CFOP>5405</CFOP><uCom>CX</uCom><qCom>3.0000</qCom><vUnCom>57.3800000000</vUnCom><vProd>172.14</vProd><cEANTrib>7896007865970</cEANTrib><uTrib>UNI</uTrib><qTrib>36.0000</qTrib><vUnTrib>4.7816666667</vUnTrib><indTot>1</indTot></prod><imposto><ICMS><ICMS60><orig>0</orig><CST>60</CST><vBCSTRet>182.73</vBCSTRet><pST>18.0000</pST><vICMSSubstituto>19.72</vICMSSubstituto><vICMSSTRet>12.62</vICMSSTRet></ICMS60></ICMS><PIS><PISAliq><CST>01</CST><vBC>172.14</vBC><pPIS>1.6500</pPIS><vPIS>2.84</vPIS></PISAliq></PIS><COFINS><COFINSAliq><CST>01</CST><vBC>172.14</vBC><pCOFINS>7.6000</pCOFINS><vCOFINS>13.08</vCOFINS></COFINSAliq></COFINS></imposto></det><total><ICMSTot><vBC>172.27</vBC><vICMS>31.00</vICMS><vICMSDeson>0.00</vICMSDeson><vFCP>0.00</vFCP><vBCST>0.00</vBCST><vST>0.00</vST><vFCPST>0.00</vFCPST><vFCPSTRet>0.00</vFCPSTRet><vProd>1638.67</vProd><vFrete>0.00</vFrete><vSeg>0.00</vSeg><vDesc>0.00</vDesc><vII>0.00</vII><vIPI>0.00</vIPI><vIPIDevol>0.00</vIPIDevol><vPIS>22.72</vPIS><vCOFINS>104.62</vCOFINS><vOutro>0.00</vOutro><vNF>1638.67</vNF></ICMSTot></total><transp><modFrete>0</modFrete><vol><qVol>17</qVol><esp>Volumes</esp><pesoL>75.770</pesoL><pesoB>90.949</pesoB></vol></transp><cobr><fat><nFat>805586</nFat><vOrig>1638.67</vOrig><vDesc>0.00</vDesc><vLiq>1638.67</vLiq></fat><dup><nDup>001</nDup><dVenc>2021-09-16</dVenc><vDup>1638.67</vDup></dup></cobr><pag><detPag><tPag>14</tPag><vPag>1638.67</vPag></detPag></pag><infAdic><infCpl>; RECEBE SABADO ATE 10H ; O ICMS SOBRE O FRETE FOI DEBITADO NO REGISTRO DE APURACAO DO ICMS DO REMENTENTE ; HORTIFRUTI FARTURA LJ 02 ; LOTE 104017 ; PED 921231 ; RAMO ATV VAREJAO CEL ( ) ; VENDA A PRAZO-ITAU-28 DIAS ; [MANDADO DE SEGURANCA (120) N 5005078-87 2017 4 03 6105] ; BC ICMS ST: 1 488,94 - ICMS ST: 124,01 ; ENTREGA - ENDERECO: RUA JORGE DE FIGUEIREDO CORREA, 1727 BAIRRO: CHAC PRIMAVERA CEP: 13087490 ; REFERENCIA: RUA JORGE DE FIGUEIREDO CORREA, 1727 ; CONF ARTIGO 313-W DO RICMS ; BC RED</infCpl></infAdic></infNFe><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /><SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1" /><Reference URI="#NFe35210803259185000141550010008411981008412000"><Transforms><Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" /><Transform Algorithm="http://www.w3.org/TR/2001/REC-xml-c14n-20010315" /></Transforms><DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1" /><DigestValue>ZMDym6D4eoXt6s7aKrHdAbv3/Wc=</DigestValue></Reference></SignedInfo><SignatureValue>FUsyRra3upNN4RX9Whb9bgr6cCm0pvlOCZnX3DGHDkwWn/WqVzyj2WO2OYmjrzJWQuFTypfIazEvOmaF8+kxM1Pas177ZBYgnbd/zi6C960YuT85E3yjPAkcoclNAJNQCiEqO1huK9Ak54Mgvzzk7oTNeKGM9DSdET2gZivYRmTlzGOL+uToEpmayxBrhOODh3igxqry2Rc5/zDNTLEQbRg4BXXdzcGpjTGDpTgyf2ekAfkV32FlBqyLKzJ5vN/sLG5wBfKAfrXMmmWO9keYfcNnriI+Zy4oblA4INWG6K+RUTzGX6izec+GPq567aNVm8cErjib4M/ztRVaqwHUVg==</SignatureValue><KeyInfo><X509Data><X509Certificate>MIIIDTCCBfWgAwIBAgIQJ+4823c1KgnMmHvuIbr10DANBgkqhkiG9w0BAQsFADB4MQswCQYDVQQGEwJCUjETMBEGA1UEChMKSUNQLUJyYXNpbDE2MDQGA1UECxMtU2VjcmV0YXJpYSBkYSBSZWNlaXRhIEZlZGVyYWwgZG8gQnJhc2lsIC0gUkZCMRwwGgYDVQQDExNBQyBDZXJ0aXNpZ24gUkZCIEc1MB4XDTIxMDcxNjE3MTYwOVoXDTIyMDcxNjE3MTYwOVowgfoxCzAJBgNVBAYTAkJSMRMwEQYDVQQKDApJQ1AtQnJhc2lsMQswCQYDVQQIDAJTUDERMA8GA1UEBwwIQ2FtcGluYXMxEzARBgNVBAsMClByZXNlbmNpYWwxFzAVBgNVBAsMDjAxMzIxNzYxMDAwMTA4MTYwNAYDVQQLDC1TZWNyZXRhcmlhIGRhIFJlY2VpdGEgRmVkZXJhbCBkbyBCcmFzaWwgLSBSRkIxFjAUBgNVBAsMDVJGQiBlLUNOUEogQTExODA2BgNVBAMML0FWRUMgQ0FNUElOQVMgRElTVFJJQlVJRE9SQSBMVERBOjAzMjU5MTg1MDAwMTQxMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApgE4zcQafNlDS2vayokCTwEW1uM/2DzVP0KVQLwbvotzXt4OdimWUIy8ackcXKt2XBFH792VsVdDiChaUCqn+eRwmYuqF/PYIqRdnjLg5uW/DtcyD/uZBeE65WsuxZbMNzkz5ak+IPVAet4rVSUFPl4Y+PHstDFzNrdopLvNs4xmwETKDxaaCvlHi15r6lXWGnz4r19VznV/qUu0H1IXKm0jqjQHXJVaVdS1BRRvp2VUtAQIP2S5jyqxh504Aji/E3h4M++OanPhsQeBJs0SCTWpqjTVQhqg4Gf22o5FETDbNHBIus96yxzKJv9jsDaEQyXzQbsaapl6Qrmuy+qqZQIDAQABo4IDDjCCAwowgb0GA1UdEQSBtTCBsqA9BgVgTAEDBKA0BDIxOTAyMTk2MDA0MzA1MTIyODcxMDAwMDAwMDAwMDAwMDAwMDAwMTM0MDI1MzVTU1BTUKAgBgVgTAEDAqAXBBVXQUxURVIgVEVMRVMgREUgU09VWkGgGQYFYEwBAwOgEAQOMDMyNTkxODUwMDAxNDGgFwYFYEwBAwegDgQMMDAwMDAwMDAwMDAwgRtDT05UQVRPQEFWRUNDQU1QSU5BUy5DT00uQlIwCQYDVR0TBAIwADAfBgNVHSMEGDAWgBRTfX+dvtFh0CC62p/jiacTc1jNQjB/BgNVHSAEeDB2MHQGBmBMAQIBDDBqMGgGCCsGAQUFBwIBFlxodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9zaXRvcmlvL2RwYy9BQ19DZXJ0aXNpZ25fUkZCL0RQQ19BQ19DZXJ0aXNpZ25fUkZCLnBkZjCBvAYDVR0fBIG0MIGxMFegVaBThlFodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9zaXRvcmlvL2xjci9BQ0NlcnRpc2lnblJGQkc1L0xhdGVzdENSTC5jcmwwVqBUoFKGUGh0dHA6Ly9pY3AtYnJhc2lsLm91dHJhbGNyLmNvbS5ici9yZXBvc2l0b3Jpby9sY3IvQUNDZXJ0aXNpZ25SRkJHNS9MYXRlc3RDUkwuY3JsMA4GA1UdDwEB/wQEAwIF4DAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwQwgawGCCsGAQUFBwEBBIGfMIGcMF8GCCsGAQUFBzAChlNodHRwOi8vaWNwLWJyYXNpbC5jZXJ0aXNpZ24uY29tLmJyL3JlcG9zaXRvcmlvL2NlcnRpZmljYWRvcy9BQ19DZXJ0aXNpZ25fUkZCX0c1LnA3YzA5BggrBgEFBQcwAYYtaHR0cDovL29jc3AtYWMtY2VydGlzaWduLXJmYi5jZXJ0aXNpZ24uY29tLmJyMA0GCSqGSIb3DQEBCwUAA4ICAQC3yVdn5dI2wCsvnLTLz8zx1wk8GJbfee4rdmuBLscIo9eJhoTTFRUwin6r6h7ztBpps0gtYfgYZCeK76CsaqvlX/mQGxkEUIfmAMhpSQcOjWeNHAfeK2zBtWj8t/quYOU+p6OhOr9uTDnX9Vvt+5fZslMtA/Ozl7XdodxhDVkVhNLrZ0OQlLTYRXg/nKMHu9Ne7XKbGM9OHU021FWrH0KYCKo3Thw44tmfdH5RKM/JlVuwUhKA9N2vhvIZwPqLo1WqEBfqZWKUum1c45zkpO6G2oIqrJ/WVDof2+UYIa35RoqfsE8gKeh3sSCkgAO8APuxmxRz+nt6AWt0wLag50NUgvqvn4MUjgKhJJXK1xrI4jFBQdb3RepO2uVKpa8RJiIwdJz9nxkjtjQh3ggNA4RyB79A3uyBYZKEVYWkIwhE43Dc5QNscBo8CVoS7zIrgEa9tkH+7QQcQn3ID/uv1u3geNqdgPMlWX702k3x83vanaeGUV+/Q6Z8cnsaGIJ6DgnVId2qWjxlLyTsQHxVo44L244g1Ltd2IIv3J/JwY9wHYrIT55SYkoqrz0B6YNhwHuqbZyEm1AuJ1M0SXJL9hKqSHo+cl4KCsPDl7k8Jf21GmM5qTK3WZt1KcqJocoU9BdD+6GZurUSykLxfH2zQxjKXRezDuQhAJChjfc+wc0Sfg==</X509Certificate></X509Data></KeyInfo></Signature></NFe><protNFe versao="4.00"><infProt Id="Id135210950577982"><tpAmb>1</tpAmb><verAplic>SP_NFE_PL009_V4</verAplic><chNFe>35210803259185000141550010008411981008412000</chNFe><dhRecbto>2021-08-18T12:53:01-03:00</dhRecbto><nProt>135210950577982</nProt><digVal>ZMDym6D4eoXt6s7aKrHdAbv3/Wc=</digVal><cStat>100</cStat><xMotivo>Autorizado o uso da NF-e</xMotivo></infProt></protNFe></nfeProc>

**Comment by GabrielMendesdc** [comment]
[35210803259185000141550010008411981008412000.zip](https://github.com/cleitonleonel/xml2pdf/files/7669460/35210803259185000141550010008411981008412000.zip)

**Comment by GabrielMendesdc** [comment]
muito obrigado pela sua atenção, estou a algumas semanas tentando converter XML pra PDF mas tá difícil

**Comment by cleitonleonel** [comment]
> muito obrigado pela sua atenção, estou a algumas semanas tentando converter XML pra PDF mas tá difícil

Se for algo muito urgente vc pode usar esse https://arquivei.com.br/conversor-xml-danfe/ , pois estive olhando seu arquivo e ele se trata de uma Nfe, o conversor.py que fiz gera apenas nfce no momento, estou criando um novo método para Nfe, mas pode demorar algum tempo para ficar pronto.

**Comment by GabrielMendesdc** [comment]
Muito obrigado pela atenção, preciso de algo que eu possa implementar em python, em um bot telegram que retornaria notas (xml) em pdf.
mas eu posso esperar o seu novo método sem problema algum ^^
grato por tudo
